---
- name: set the definitive project ID
  ansible.builtin.set_fact:
    project_id: '{{ hash_list[0].projectId if ( hash_list != [] ) else None }}'
  failed_when: "hash_list == []"

- name: create the billing group
  raphaeldegail.googlecloudy.gcp_cloudidentity_group:
    groupKey:
      id: '{{ billing_group_email }}'
    parent: 'customers/{{ directory_customer_id }}'
    displayName: '{{ billing_group_name }}'
    description: 'Group of identities with billing users permission.'
    labels:
      cloudidentity.googleapis.com/groups.discussion_forum:
  register: google_group

- name: add the builder account to the group
  raphaeldegail.googlecloudy.gcp_cloudidentity_group_membership:
    preferredMemberKey:
      id: '{{ builder_account.name }}@{{ project_id }}.iam.gserviceaccount.com'
    roles:
      - name: 'MANAGER'
      - name: 'MEMBER'
    group_id: '{{ ( google_group.name | split("/") )[-1] }}'

- name: set IAM policy for the group
  raphaeldegail.googlecloudy.gcp_billing_account_iam:
    bindings:
      - role: roles/billing.user
        members: ['group:{{ billing_group_email }}']
    policy_version: '{{ policy_version }}'
    billingaccount_id: '{{ gcp_billing_account_id }}'
