---
argument_specs:
  main:
    short_description: Fetch a GCP organization name from its domain name.
    description:
      - Fetch GCP info about an organization from its domain name.
      - the organization name and directory customer ID are retrieved.
    author:
      - Raphaël de Gail
    options:
      root_project:
        type: 'dict'
        required: true
        description:
          - The definition of the root project.
        options:
          base_name:
            type: 'str'
            required: true
            description:
              - The user-friendly name of the project.
          labels:
            type: 'dict'
            required: true
            descrption:
              - A map of kay/value characterizing the project.
          services:
            type: 'list'
            elements: 'str'
            required: true
            description:
              - A list of services to enable in the project.
 