--- 
- name: List all available projects
  google.cloud.gcp_resourcemanager_project_info:
  register: all_projects

- name: Filter projects with matching labels
  ansible.builtin.set_fact:
    hash_list: "{{ all_projects | community.general.json_query(query1) }}"
  failed_when: "hash_list | length > 1"
  vars:
    query1: "resources[?lifecycleState=='ACTIVE' && labels==`{{ root_project.labels | to_json }}`]"
