---
argument_specs:
  main:
    short_description: Configure access to the billing account
    description:
      - Create the Google group for billing users.
      - Add the builder account to the Google group.
      - Set billing usage access to the Google group for the billing account.
    author:
      - Raphaël de Gail
    options:
      billing_group_email:
        type: 'str'
        required: true
        description:
          - The email address of the billing group.
      directory_customer_id:
        type: 'str'
        required: true
        description:
          - The ID of the customer directory hosting the Google group.
      billing_group_name:
        type: 'str'
        required: true
        description:
          - The user-friendly name of the group.
      builder_account:
        type: 'dict'
        required: true
        description:
          - The definition of the builder service account.
        options:
          name:
            type: 'str'
            required: true
            description:
              - The name of the builder service account.
          display_name:
            type: 'str'
            required: true
            description:
              - The user-friendly name of the builder service account.
      gcp_billing_account_id:
        type: 'str'
        required: true
        description:
          - The ID of the billing account linked to the google group.
