---
argument_specs:
  main:
    short_description: Initializes the organization IAM policy for the root structure
    description:
      - Set up RBAC for basic groups of GCP organization.
      - the administrators group with roleAdmin and orgadmin roles.
      - the finops group with finops role.
      - the organization policy group with policy role.
      - one external owner that remains organization admin.
    author:
      - Raphaël de Gail
    options:
      organization_id:
        type: "str"
        required: true
        description:
          - The ID for the GCP organization.
      finops_group:
        type: "str"
        required: true
        description:
          - the finops group email address.
      admins_group:
        type: "str"
        required: true
        description:
          - the administrators group email address.
      policy_group:
        type: "str"
        required: true
        description:
          - the organization policy group email address.
      external_owner:
        type: "str"
        required: true
        description:
          - the external owner email address.
