---
argument_specs:
  main:
    short_description: Set up the HCP Terraform project for the root structure
    description:
      - Create a project in a HCP Terraform organization.
    author:
      - Raphaël de Gail
    options:
      workspaces_folder:
        type: 'dict'
        required: true
        description:
          - The workspace folder definition.
        options:
          display_name:
            type: 'str'
            required: true
            description:
              - The display name of the workspace folder.          
      hcp_tf_organization:
        type: 'str'
        required: true
        description:
          - the name of the HCP Terraform organization hosting the project.